id: ACE200B53
base_file: fD453.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:04:42.389092
  last_modified_at: 2022-05-30 21:04:42.389101
